### ISSUE TITLE
Could you provide us with the data folder?

### ISSUE THREAD

**Issue by wxj630** [thumbe3/label-noise-nlp#1]
Could you provide us with the data folder? also embedding files that may be required

**Comment by sid7954** [comment]
The data file should contain one sample per line in the format: 
* \<Sentence\> <\Tab> \<Label\>

The add_noise.py script changes this format to the following (one sample per line):
*  \<Sentence\> <\Tab> \<Noisy Label\> <\Tab> \<Did original label change\> <\Tab> \<Original Label\>
 
For example consider a sentence A with original label 2, if the noise is able to perturb this label to say 4 then the file will contain: “A <\Tab> 4 <\Tab> 1 <\Tab> 2” , else it will contain: “A <\Tab> 2 <\Tab> 0 <\Tab> 2".

**Comment by sid7954** [comment]
With regards to the data folder and embedding file: 
* The data files are the standard datasets (available online) 
* The embedding file is the Wikipedia 2014 + Gigaword 5 (6B tokens, 400K vocab, uncased, 300d vectors, 822 MB download) file provided at https://github.com/stanfordnlp/GloVe
