### ISSUE TITLE
Order of the scripts to run

### ISSUE THREAD

**Issue by nargesam** [thumbe3/label-noise-nlp#2]
Hi, 

can you please provide more info on the order of scripts to run for this repo?

**Comment by sid7954** [comment]
Hi Narges,

The code needs to run in the following order: 

* Start with a data file having `<Sentence> <\Tab> <Label>` per line.
* Run the add_noise.py script specifying the type of noise, level of noise, dataset and number of classes: 
  `python add_noise.py --mode <NOISE MODE> --noise <NOISE FRACTION> --dataset <DATASET NAME> --num_classes <NUMBER OF LABEL CLASSES>` 
 An example: Adding random noise (mode 0) with 20% of all sentence labels changed for the ag_news dataset having 4 class labels : `python add_noise.py --mode 0 --noise 0.2 --dataset ag_news --num_classes 4`

* Train the classifier and the noise model: 
 `python train_classifier.py --noise <NOISE MODE> <--cnn OR --lstm> --dataset <DATASET NAME> --max_epoch <TOTAL EPOCHS> --warmup <WARMUP EPOCHS> --result <OUTPUT-DIRECTORY>`
 An example: Running a CNN classifier for ag_news with random noise (mode 0) with total epochs 30 and warmup epochs 7: `python train_classifier.py --noise 0 --cnn --dataset ag_news --max_epoch 30 --warmup 7 --result output_directory`

Other bash scripts (like run_ag_hard_label.sh, run_ag_baseline_label.sh, run_batch_soft.sh, etc) are for running the code on an entire dataset for different noise levels.
